# Site settings
title: Srishti Nema
description: >- # this means to ignore newlines until "baseurl:"
  Computer Science student, programmer, curious learner, avid reader and novice writer. Likes to wonder. A lot.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: YoussefRaafatNasry/portfolYOU


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Srishti Nema
  image    : assets/images/avatar_form.jpg
  email    : srishtinema.0699@gmail.com
  github   : srishti-nema
  twitter  : srishtinema
  linkedin : srishtinema
  #facebook : username


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
